# Generated by Django 3.2.7 on 2021-09-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=models.CharField(choices=[('ok', 'ok'), ('nay', 'nay'), ('hold', 'hold')], default='hold', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
