# Generated by Django 3.1.6 on 2021-07-11 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 6, 23, 59, 14749, tzinfo=utc)),
        ),
    ]
